import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.content_container}>
          <div className={styles.content}>
          <h1>Sean Chester</h1>
          <h2 className={styles.job_title}>Software Developer</h2>
          <p>Read more about me or contact me</p>
        </div>
       </div>
      </main>
    </div>
  )
}
